# Generated by Django 5.2 on 2025-04-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingconfig',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='multiplier_1_to_2hr',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='multiplier_2_to_3hr',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='multiplier_upto_1hr',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='time_multipliers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='day_of_week',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='waiting_charge_unit_minutes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='waiting_time_free_minutes',
            field=models.IntegerField(),
        ),
    ]
